# Generated by Django 5.2.4 on 2025-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='nickname'),
        ),
    ]
